[package]
name = "moa-dlp"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
moa-memory-pii = { workspace = true }
rand.workspace = true
secrecy = { workspace = true }
thiserror.workspace = true
tracing = { workspace = true }
workspace-hack = { workspace = true }
