[package]
name = "moa-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
moa-core = { path = "../moa-core" }
moa-orchestrator-client = { path = "../moa-orchestrator-client" }
tokio.workspace = true
uuid.workspace = true
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
memory-graph = { package = "moa-memory-graph", path = "../moa-memory/graph" }
moa-session = { path = "../moa-session" }
mockito = "1"
serde_json.workspace = true
sqlx = { workspace = true, features = ["tls-rustls"] }
uuid.workspace = true
