import { useMemo } from "react";
import { Edit3, Trash2 } from "lucide-react";

import type { PageSummaryDto, WikiPageDto } from "@/lib/bindings";
import { Markdown } from "@/components/prompt-kit/markdown";
import { Source, SourceContent, SourceTrigger } from "@/components/prompt-kit/source";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Separator } from "@/components/ui/separator";
import { formatAbsoluteDate } from "@/lib/utils";
import {
  replaceWikiLinks,
  resolveMemoryTarget,
  WikiLink,
} from "@/components/memory/wiki-link";

type MemoryPageViewerProps = {
  page: WikiPageDto;
  pages: PageSummaryDto[];
  onDelete: () => void;
  onEdit: () => void;
  onNavigate: (path: string) => void;
};

/**
 * Read-only memory page renderer with markdown and related references.
 */
export function MemoryPageViewer({
  page,
  pages,
  onDelete,
  onEdit,
  onNavigate,
}: MemoryPageViewerProps) {
  const resolveTarget = (target: string) =>
    resolveMemoryTarget(target, pages, page.path);

  const markdown = useMemo(
    () => replaceWikiLinks(page.content, resolveTarget),
    [page.content, pages, page.path],
  );

  const relatedItems = useMemo(
    () => page.related.map((reference) => buildReference(reference, pages, page.path)),
    [page.path, page.related, pages],
  );
  const sourceItems = useMemo(
    () => page.sources.map((reference) => buildReference(reference, pages, page.path)),
    [page.path, page.sources, pages],
  );

  return (
    <ScrollArea className="h-full">
      <div className="mx-auto flex w-full max-w-5xl flex-col gap-6 px-6 py-6">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div className="min-w-0">
            <p className="text-[11px] uppercase tracking-widest text-muted-foreground">
              Memory page
            </p>
            <h1 className="mt-1 text-2xl font-semibold">{page.title}</h1>
            <p className="mt-2 break-all text-sm text-muted-foreground">
              {page.path ?? "Unsaved page"}
            </p>
          </div>

          <div className="flex items-center gap-2">
            <Button onClick={onEdit} type="button" variant="secondary">
              <Edit3 className="h-4 w-4" />
              Edit
            </Button>
            <Button onClick={onDelete} type="button" variant="outline">
              <Trash2 className="h-4 w-4" />
              Delete
            </Button>
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <Badge variant="secondary">{page.pageType}</Badge>
          <Badge variant="outline">{page.confidence}</Badge>
          {page.autoGenerated ? <Badge variant="outline">auto-generated</Badge> : null}
          {page.tags.map((tag) => (
            <Badge key={tag} variant="outline">
              {tag}
            </Badge>
          ))}
        </div>

        <div className="grid gap-3 text-sm text-muted-foreground md:grid-cols-2 xl:grid-cols-4">
          <MetadataItem label="Created" value={formatAbsoluteDate(page.created)} />
          <MetadataItem label="Updated" value={formatAbsoluteDate(page.updated)} />
          <MetadataItem
            label="Last referenced"
            value={formatAbsoluteDate(page.lastReferenced)}
          />
          <MetadataItem label="References" value={String(page.referenceCount)} />
        </div>

        <Separator />

        <div className="space-y-6">
          <Markdown
            className="space-y-4 text-sm leading-7"
            components={{
              a: ({ href, children }) => (
                <WikiLink href={href} onNavigate={onNavigate}>
                  {children}
                </WikiLink>
              ),
            }}
          >
            {markdown}
          </Markdown>

          {relatedItems.length ? (
            <section className="space-y-3">
              <div>
                <p className="text-[11px] uppercase tracking-widest text-muted-foreground">
                  Related pages
                </p>
                <h2 className="mt-1 text-sm font-semibold">Cross references</h2>
              </div>
              <div className="flex flex-wrap gap-2">
                {relatedItems.map((item) => (
                  <Source
                    external={item.external}
                    href={item.href}
                    key={`related:${item.reference}`}
                    onNavigate={item.path ? () => onNavigate(item.path!) : undefined}
                  >
                    <SourceTrigger label={item.label} />
                    <SourceContent
                      description={item.description}
                      title={item.title}
                    />
                  </Source>
                ))}
              </div>
            </section>
          ) : null}

          {sourceItems.length ? (
            <section className="space-y-3">
              <div>
                <p className="text-[11px] uppercase tracking-widest text-muted-foreground">
                  Sources
                </p>
                <h2 className="mt-1 text-sm font-semibold">Origin references</h2>
              </div>
              <div className="flex flex-wrap gap-2">
                {sourceItems.map((item) => (
                  <Source
                    external={item.external}
                    href={item.href}
                    key={`source:${item.reference}`}
                    onNavigate={item.path ? () => onNavigate(item.path!) : undefined}
                  >
                    <SourceTrigger label={item.label} showFavicon={item.external} />
                    <SourceContent
                      description={item.description}
                      title={item.title}
                    />
                  </Source>
                ))}
              </div>
            </section>
          ) : null}
        </div>
      </div>
    </ScrollArea>
  );
}

function buildReference(
  reference: string,
  pages: PageSummaryDto[],
  currentPath?: string | null,
) {
  const external = /^https?:\/\//i.test(reference);
  const path = external ? null : resolveMemoryTarget(reference, pages, currentPath);
  const matchingPage = path ? pages.find((page) => page.path === path) : null;
  const label = matchingPage?.title ?? reference.split("/").pop()?.replace(/\.md$/i, "") ?? reference;

  return {
    description: external
      ? "Open external source reference"
      : path
        ? `Open ${matchingPage?.pageType ?? "memory"} page`
        : "Memory reference not found in the active workspace",
    external,
    href: path ?? reference,
    label,
    path,
    reference,
    title: matchingPage?.title ?? reference,
  };
}

function MetadataItem({
  label,
  value,
}: {
  label: string;
  value: string;
}) {
  return (
    <div className="rounded-lg border border-border bg-card/50 px-3 py-2">
      <p className="text-[11px] uppercase tracking-widest text-muted-foreground">{label}</p>
      <p className="mt-1 text-sm text-foreground">{value}</p>
    </div>
  );
}
