[package]
name = "moa-observability"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
metrics.workspace = true
metrics-exporter-prometheus.workspace = true
moa-core = { workspace = true }
opentelemetry.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry_sdk.workspace = true
reqwest.workspace = true
tokio.workspace = true
tokio-metrics.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-opentelemetry.workspace = true
tracing-subscriber = { workspace = true, features = ["json"] }
workspace-hack = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tokio_unstable)'] }
