[package]
name = "moa-auth-providers-auth0"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[features]
default = []
auth0 = []

[dependencies]
async-trait.workspace = true
chrono = { workspace = true, features = ["serde"] }
jsonwebtoken.workspace = true
moa-authz.workspace = true
moa-authz-schema.workspace = true
moa-core.workspace = true
moka.workspace = true
reqwest = { workspace = true, features = ["form", "json", "rustls"] }
secrecy.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sqlx = { workspace = true, features = ["runtime-tokio", "tls-rustls", "postgres", "uuid", "chrono", "migrate"] }
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync"] }
tracing.workspace = true
uuid = { workspace = true, features = ["v4", "serde"] }
workspace-hack = { workspace = true }

[dev-dependencies]
base64.workspace = true
httpmock.workspace = true
rsa = { version = "0.9", features = ["pem"] }
