// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Serialized event-log row for session inspection.
 */
export type EventRecordDto = { 
/**
 * Event identifier.
 */
id: string, 
/**
 * Session identifier.
 */
sessionId: string, 
/**
 * Sequence number within the session.
 */
sequenceNum: number, 
/**
 * Event type label.
 */
eventType: string, 
/**
 * Event timestamp.
 */
timestamp: string, 
/**
 * Optional token count for the event.
 */
tokenCount: number | null, 
/**
 * Serialized event payload.
 */
payload: unknown, };
