// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Compact memory search result row.
 */
export type MemorySearchResultDto = { 
/**
 * Human-readable memory scope label.
 */
scope: string, 
/**
 * Logical page path.
 */
path: string, 
/**
 * Page title.
 */
title: string, 
/**
 * Page type label.
 */
pageType: string, 
/**
 * Search snippet.
 */
snippet: string, 
/**
 * Confidence label.
 */
confidence: string, 
/**
 * Last update timestamp.
 */
updated: string, 
/**
 * Reference count.
 */
referenceCount: number, };
