// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Error payload returned from the desktop backend to the frontend.
 */
export type MoaAppError = { "kind": "invalid_input", "message": string } | { "kind": "runtime", "message": string } | { "kind": "internal", "message": string };
