// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Runtime configuration values the frontend needs to render settings.
 */
export type MoaConfigDto = { 
/**
 * Default provider name.
 */
defaultProvider: string, 
/**
 * Default model identifier.
 */
defaultModel: string, 
/**
 * Requested reasoning effort.
 */
reasoningEffort: string, 
/**
 * Whether native provider web search is enabled.
 */
webSearchEnabled: boolean, 
/**
 * Optional workspace instructions.
 */
workspaceInstructions: string | null, 
/**
 * Optional user instructions.
 */
userInstructions: string | null, 
/**
 * Sandbox directory path.
 */
sandboxDir: string, 
/**
 * Memory directory path.
 */
memoryDir: string, 
/**
 * Whether daemon auto-connect is enabled.
 */
daemonAutoConnect: boolean, 
/**
 * Whether observability export is enabled.
 */
observabilityEnabled: boolean, 
/**
 * Deployment environment label when configured.
 */
environment: string | null, };
