// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One selectable model option for the desktop model picker.
 */
export type ModelOptionDto = { 
/**
 * Stable value sent back to the backend when selected.
 */
value: string, 
/**
 * Human-readable label shown in the UI.
 */
label: string, 
/**
 * Provider slug associated with the option.
 */
provider: string, 
/**
 * Maximum prompt context window for the model when known.
 */
contextWindow: number | null, };
