// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Compact memory page listing entry.
 */
export type PageSummaryDto = { 
/**
 * Logical page path.
 */
path: string, 
/**
 * Page title.
 */
title: string, 
/**
 * Page type label.
 */
pageType: string, 
/**
 * Confidence label.
 */
confidence: string, 
/**
 * Last update timestamp.
 */
updated: string, };
