// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of the currently selected runtime.
 */
export type RuntimeInfoDto = { 
/**
 * Active session identifier.
 */
sessionId: string, 
/**
 * Active workspace identifier.
 */
workspaceId: string, 
/**
 * Selected model identifier.
 */
model: string, 
/**
 * Local sandbox root path.
 */
sandboxRoot: string, 
/**
 * Runtime transport kind.
 */
runtimeKind: string, };
