// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Full session metadata snapshot.
 */
export type SessionMetaDto = { 
/**
 * Session identifier.
 */
id: string, 
/**
 * Workspace identifier.
 */
workspaceId: string, 
/**
 * User identifier.
 */
userId: string, 
/**
 * Optional session title.
 */
title: string | null, 
/**
 * Session lifecycle status.
 */
status: string, 
/**
 * Origin platform.
 */
platform: string, 
/**
 * Optional platform channel identifier.
 */
platformChannel: string | null, 
/**
 * Model identifier.
 */
model: string, 
/**
 * Session creation timestamp.
 */
createdAt: string, 
/**
 * Last update timestamp.
 */
updatedAt: string, 
/**
 * Completion timestamp when available.
 */
completedAt: string | null, 
/**
 * Parent session identifier when this is a child session.
 */
parentSessionId: string | null, 
/**
 * Aggregate input tokens.
 */
totalInputTokens: number, 
/**
 * Aggregate output tokens.
 */
totalOutputTokens: number, 
/**
 * Aggregate cost in cents.
 */
totalCostCents: number, 
/**
 * Persisted event count.
 */
eventCount: number, 
/**
 * Last checkpoint sequence when present.
 */
lastCheckpointSeq: number | null, };
