// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Compact session listing row for the frontend session list.
 */
export type SessionSummaryDto = { 
/**
 * Session identifier.
 */
sessionId: string, 
/**
 * Workspace identifier.
 */
workspaceId: string, 
/**
 * User identifier.
 */
userId: string, 
/**
 * Optional title.
 */
title: string | null, 
/**
 * Session lifecycle status.
 */
status: string, 
/**
 * Origin platform.
 */
platform: string, 
/**
 * Model identifier.
 */
model: string, 
/**
 * Last update timestamp.
 */
updatedAt: string, 
/**
 * Whether this is the active session in the desktop runtime.
 */
active: boolean, };
