// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionSummaryDto } from "./SessionSummaryDto";

/**
 * Session preview row used by the sidebar.
 */
export type SessionPreviewDto = { 
/**
 * Persisted session summary.
 */
summary: SessionSummaryDto, 
/**
 * Most recent conversational text when present.
 */
lastMessage: string | null, };
