// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tagged stream event sent over a Tauri channel.
 */
export type StreamEvent = { "event": "assistantStarted" } | { "event": "assistantDelta", "data": { 
/**
 * Incremental assistant text.
 */
text: string, } } | { "event": "assistantFinished", "data": { 
/**
 * Final assistant text.
 */
text: string, } } | { "event": "toolUpdate", "data": { 
/**
 * Tool call identifier.
 */
callId: string, 
/**
 * Tool name.
 */
toolName: string, 
/**
 * Simplified status label.
 */
status: string, 
/**
 * Concise one-line summary when available.
 */
summary: string | null, 
/**
 * Optional longer detail for expanded tool rendering.
 */
detail: string | null, } } | { "event": "approvalRequired", "data": { 
/**
 * Approval request identifier.
 */
requestId: string, 
/**
 * Tool name awaiting approval.
 */
toolName: string, 
/**
 * Risk level label.
 */
riskLevel: string, 
/**
 * Human-readable tool input summary.
 */
inputSummary: string, 
/**
 * Compact diff preview for the first proposed file edit.
 */
diffPreview: string | null, } } | { "event": "usageUpdated", "data": { 
/**
 * Total input + output tokens observed so far.
 */
totalTokens: number, } } | { "event": "notice", "data": { 
/**
 * Human-readable status message.
 */
message: string, } } | { "event": "turnCompleted" } | { "event": "error", "data": { 
/**
 * Error message.
 */
message: string, } };
