// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Full wiki page payload returned to the frontend editor.
 */
export type WikiPageDto = { 
/**
 * Logical page path when one exists.
 */
path: string | null, 
/**
 * Page title.
 */
title: string, 
/**
 * Page type label.
 */
pageType: string, 
/**
 * Raw markdown content.
 */
content: string, 
/**
 * Creation timestamp.
 */
created: string, 
/**
 * Last update timestamp.
 */
updated: string, 
/**
 * Confidence label.
 */
confidence: string, 
/**
 * Explicit related links.
 */
related: Array<string>, 
/**
 * Provenance sources.
 */
sources: Array<string>, 
/**
 * User-defined tags.
 */
tags: Array<string>, 
/**
 * Whether the page was auto-generated.
 */
autoGenerated: boolean, 
/**
 * Last reference timestamp.
 */
lastReferenced: string, 
/**
 * Reference count.
 */
referenceCount: number, 
/**
 * Additional preserved metadata.
 */
metadata: Record<string, unknown>, };
