[package]
name = "moa-lineage-core"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
chrono = { workspace = true, features = ["serde"] }
moa-core = { path = "../../moa-core" }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
uuid.workspace = true
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
