[package]
name = "moa-authz"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
moa-authz-schema.workspace = true
moa-core.workspace = true
reqwest.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sqlx = { workspace = true, features = ["runtime-tokio", "tls-rustls", "postgres", "json", "uuid", "chrono", "migrate"] }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid = { workspace = true, features = ["v4", "serde"] }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
httpmock = "0.7"
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "test-util"] }
