[package]
name = "xtask"
version.workspace = true
edition.workspace = true
license.workspace = true
default-run = "xtask"

[dependencies]
anyhow.workspace = true
moa-core = { workspace = true }
moa-eval = { workspace = true }
moa-memory-lifecycle = { workspace = true }
serde.workspace = true
serde_json.workspace = true
sqlx = { workspace = true, features = ["tls-rustls", "runtime-tokio-rustls", "postgres"] }
tokio.workspace = true
toml.workspace = true
workspace-hack = { workspace = true }
