[package]
name = "moa-lineage-otel"
version = "0.1.0"
edition = "2024"

[dependencies]
moa-lineage-core = { workspace = true }
opentelemetry.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-opentelemetry.workspace = true
workspace-hack = { workspace = true }

[dev-dependencies]
chrono = { workspace = true }
moa-core = { workspace = true }
moa-memory-types = { workspace = true }
opentelemetry_sdk = { workspace = true, features = ["testing"] }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
