[package]
name = "moa-security"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
age = "0.11"
async-trait.workspace = true
chrono.workspace = true
globset.workspace = true
moa-core = { workspace = true }
serde_json.workspace = true
shell-words.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
workspace-hack = { workspace = true }

[dev-dependencies]
tempfile.workspace = true
