[package]
name = "moa-workflows"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
moa-artifacts.workspace = true
moa-core.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true
workspace-hack.workspace = true

[dev-dependencies]
tokio.workspace = true
