[package]
name = "moa-scoring"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
moa-core.workspace = true
serde.workspace = true
sqlx = { workspace = true, features = ["uuid"] }
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true
workspace-hack.workspace = true
