//! Idempotent OpenFGA bootstrap for MOA.
//!
//! On each run this binary ensures the configured store exists, writes the v1
//! authorization model, runs smoke checks against a synthetic tenant
//! chain, and writes resolved authz env values to `.env.fga` for shell sourcing.

use anyhow::{Context, Result, bail};
use clap::Parser;
use moa_authz_schema::SCHEMA_V1_JSON;
use std::path::PathBuf;
use uuid::Uuid;

mod http;

#[derive(Parser, Debug)]
struct Args {
    /// OpenFGA HTTP base URL.
    #[arg(
        long,
        env = "MOA_AUTHZ_OPENFGA_URL",
        default_value = "http://localhost:10030"
    )]
    url: String,

    /// Preshared key for local OpenFGA.
    #[arg(long, env = "MOA_AUTHZ_OPENFGA_PRESHARED_KEY")]
    preshared_key: String,

    /// Store name. Existing stores with this name are reused.
    #[arg(long, env = "MOA_AUTHZ_OPENFGA_STORE_NAME", default_value = "moa")]
    store_name: String,

    /// Path for the generated shell env file.
    #[arg(long, env = "MOA_FGA_ENV_OUTPUT", default_value = ".env.fga")]
    env_output: PathBuf,

    /// Skip smoke checks. Intended only for CI bootstrapping.
    #[arg(long, env = "MOA_FGA_BOOTSTRAP_SKIP_SMOKE", default_value_t = false)]
    skip_smoke: bool,
}

#[tokio::main]
async fn main() -> Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .compact()
        .init();

    let args = Args::parse();
    let client = http::FgaClient::new(&args.url, &args.preshared_key)?;

    let store_id = match client.find_store_by_name(&args.store_name).await? {
        Some(id) => {
            tracing::info!(store_id = %id, store_name = %args.store_name, "reusing OpenFGA store");
            id
        }
        None => {
            let id = client.create_store(&args.store_name).await?;
            tracing::info!(store_id = %id, store_name = %args.store_name, "created OpenFGA store");
            id
        }
    };

    let model = serde_json::from_str(SCHEMA_V1_JSON).context("parse embedded OpenFGA model")?;
    let model_id = client
        .write_authorization_model(&store_id, &model)
        .await
        .context("write authorization model")?;
    tracing::info!(model_id = %model_id, "wrote schema v1 model");

    if !args.skip_smoke {
        run_smoke_checks(&client, &store_id, &model_id).await?;
    }

    let env_content = format!(
        "# generated by moa-fga-bootstrap; safe to re-source\n\
         MOA_AUTHZ_OPENFGA_URL={}\n\
         MOA_AUTHZ_OPENFGA_PRESHARED_KEY={}\n\
         MOA_AUTHZ_OPENFGA_STORE_ID={}\n\
         MOA_AUTHZ_OPENFGA_MODEL_ID={}\n",
        args.url, args.preshared_key, store_id, model_id,
    );
    tokio::fs::write(&args.env_output, &env_content)
        .await
        .with_context(|| format!("write {}", args.env_output.display()))?;
    println!("{env_content}");

    Ok(())
}

async fn run_smoke_checks(client: &http::FgaClient, store_id: &str, model_id: &str) -> Result<()> {
    let workspace_id = moa_core::WORKSPACE_ID;
    let tenant_id =
        Uuid::parse_str("00000000-0000-0000-0000-00000000ffff").context("parse smoke tenant id")?;
    let user_id =
        Uuid::parse_str("00000000-0000-0000-0000-00000000fffd").context("parse smoke user id")?;
    let agent_id =
        Uuid::parse_str("00000000-0000-0000-0000-00000000fffc").context("parse smoke agent id")?;
    let session_id = Uuid::parse_str("00000000-0000-0000-0000-00000000fffb")
        .context("parse smoke session id")?;
    let contact_id = Uuid::parse_str("00000000-0000-0000-0000-00000000fffa")
        .context("parse smoke contact id")?;

    let smoke_tuples = [
        serde_json::json!({
            "user": format!("operator:{user_id}"),
            "relation": "admin",
            "object": format!("workspace:{workspace_id}"),
        }),
        serde_json::json!({
            "user": format!("workspace:{workspace_id}"),
            "relation": "workspace",
            "object": format!("tenant:{tenant_id}"),
        }),
        serde_json::json!({
            "user": format!("tenant:{tenant_id}"),
            "relation": "tenant",
            "object": format!("agent:{agent_id}"),
        }),
        serde_json::json!({
            "user": format!("tenant:{tenant_id}"),
            "relation": "tenant",
            "object": format!("session:{session_id}"),
        }),
        serde_json::json!({
            "user": format!("contact:{contact_id}"),
            "relation": "contact",
            "object": format!("session:{session_id}"),
        }),
    ];

    client
        .delete_tuples_raw_best_effort(store_id, model_id, &smoke_tuples)
        .await;
    client
        .write_tuples_raw(store_id, model_id, &smoke_tuples)
        .await
        .context("write smoke tuples")?;

    let tenant = format!("tenant:{tenant_id}");
    let agent = format!("agent:{agent_id}");
    let session = format!("session:{session_id}");
    let user = format!("operator:{user_id}");
    let contact = format!("contact:{contact_id}");
    let admin_check = client
        .check(store_id, model_id, &user, "admin", &tenant)
        .await?;
    if !admin_check {
        bail!("smoke Check failed: tenant admin expected to administer tenant");
    }
    tracing::info!("smoke Check ok: tenant admin");

    let listed = client
        .list_objects(store_id, model_id, "tenant", "admin", &user)
        .await?;
    if !listed.contains(&tenant) {
        bail!(
            "smoke ListObjects failed: expected {} in {:?}",
            tenant,
            listed
        );
    }
    tracing::info!("smoke ListObjects ok");

    let batch = client
        .batch_check(
            store_id,
            model_id,
            &[
                (user.clone(), "admin".to_string(), tenant.clone()),
                (user.clone(), "operator".to_string(), tenant),
                (user.clone(), "operator".to_string(), agent),
                (user, "participant".to_string(), session.clone()),
                (contact, "participant".to_string(), session),
            ],
        )
        .await?;
    if batch != [true, true, true, true, true] {
        bail!("smoke BatchCheck failed: expected [true, true, true, true, true], got {batch:?}");
    }
    tracing::info!("smoke BatchCheck ok");

    client
        .delete_tuples_raw(store_id, model_id, &smoke_tuples)
        .await
        .context("cleanup smoke tuples")?;

    Ok(())
}
